sudo: false
language: rust
cache: cargo

matrix:
  include:
    - rust: stable
      env: RUST_VERSION=stable

    - rust: beta
      env: RUST_VERSION=beta

    - rust: nightly
      env: RUST_VERSION=nightly

addons:
  apt:
    packages:
      - redis-server

script:
  - make test
  - cargo check --benches
  - |
    [ "$RUST_VERSION" = "nightly" ] && exit 0 # Don't cargo-fmt on nightly
    rustup component add rustfmt
    cargo fmt --all -- --check

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#pocoo"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
