pre-release-replacements = [ {file="CHANGELOG.md", search="...master", replace="...{{version}}"}, {file="CHANGELOG.md", search="HEAD", replace="{{version}}"}, {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}"} ]
pre-release-hook = "scripts/update-versions.sh"
tag-name = "{{version}}"
