[profile.default]
retries = 2
test-threads = 1
failure-output = "immediate-final" # show test failures inline, and also at the end of the run
fail-fast = false # run all tests, even if some failed
slow-timeout = { period = "5s", terminate-after = 4 }
